import React, { useState, useEffect, useMemo } from "react";
import { useNavigate, useParams, useLocation } from "react-router-dom";
import NavBar from "../../components/auth/Navbar";
import Toast from "../../components/common/Toast";
import apiClient, { opportunities, applications, getApiErrorMessage } from "../../services/api";

function getCustomQuestions(opportunityId) {
  try {
    const q = JSON.parse(sessionStorage.getItem("opportunityCustomQuestions") || "{}");
    return Array.isArray(q[opportunityId]) ? q[opportunityId] : [];
  } catch (_) {
    return [];
  }
}

const ApplyApplication = () => {
  const navigate = useNavigate();
  const { opportunityId } = useParams();
  const location = useLocation();
  const [opportunity, setOpportunity] = useState(null);
  const [loading, setLoading] = useState(true);
  const [toast, setToast] = useState({ isOpen: false, message: "", type: "success" });
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    aboutMe: "",
    motivation: "",
  });
  const [cvFile, setCvFile] = useState(null);
  const [profileCvUrl, setProfileCvUrl] = useState(null);
  const [profileCvName, setProfileCvName] = useState(null);
  const [profileCvId, setProfileCvId] = useState(null)
  const [uploadingProfileCv, setUploadingProfileCv] = useState(false);
  const [customAnswers, setCustomAnswers] = useState({});

  const [existingApplication, setExistingApplication] = useState(null);
  const [isEditMode, setIsEditMode] = useState(false);

  const customQuestions = useMemo(
    () => (opportunityId ? getCustomQuestions(opportunityId) : []),
    [opportunityId]
  );

  useEffect(() => {
    const job = location.state?.job;
    const app = location.state?.existingApplication;
    const editMode = location.state?.isEdit;
    if (app) {
      setExistingApplication(app);
      setIsEditMode(!!editMode);
      // If the stored application contains a rich cover letter (generated by
      // this form on submit), parse it and pre-fill the individual fields so
      // the user sees only what they originally entered for each section.
      const parseCoverLetter = (text) => {
        if (!text || typeof text !== 'string') return {};
        const out = {};
        // Sections we produce on submit: Contact details, About me, Why I am applying,
        // Additional questions and answers
        const sections = {};
        // Split by known headings, keep order
        const headings = ["Contact details:", "About me:", "Why I am applying:", "Additional questions and answers:"];
        // Normalize line endings
        const normalized = text.replace(/\r\n/g, "\n");
        // Find indices of headings
        const indices = {};
        headings.forEach((h) => {
          const idx = normalized.indexOf(h);
          if (idx !== -1) indices[h] = idx;
        });
        // Sort found headings by position
        const sorted = Object.keys(indices).sort((a, b) => indices[a] - indices[b]);
        for (let i = 0; i < sorted.length; i++) {
          const h = sorted[i];
          const start = indices[h] + h.length;
          const end = i + 1 < sorted.length ? indices[sorted[i + 1]] : normalized.length;
          sections[h] = normalized.slice(start, end).trim();
        }

        // Contact details: extract Full name and Email lines
        if (sections["Contact details:"]) {
          const lines = sections["Contact details:"].split('\n').map(s => s.trim()).filter(Boolean);
          lines.forEach((ln) => {
            const mName = ln.match(/^Full name:\s*(.+)$/i);
            const mEmail = ln.match(/^Email:\s*(.+)$/i);
            if (mName) out.name = mName[1].trim();
            if (mEmail) out.email = mEmail[1].trim();
          });
        }

        // About me
        if (sections["About me:"]){
          out.aboutMe = sections["About me:"].replace(/^\s+|\s+$/g, "");
        }

        // Motivation
        if (sections["Why I am applying:"]) {
          out.motivation = sections["Why I am applying:"].replace(/^\s+|\s+$/g, "");
        }

        // Parse additional questions (Q: / A: blocks)
        if (sections["Additional questions and answers:"]) {
          const block = sections["Additional questions and answers:"];
          const qaRegex = /Q:\s*(.+)\nA:\s*([\s\S]*?)(?=\n\nQ:|$)/g;
          const matches = [...block.matchAll(qaRegex)];
          const qas = {};
          matches.forEach((m) => {
            const qText = m[1].trim();
            const ans = m[2].trim();
            qas[qText] = ans;
          });
          out.qaByText = qas;
        }

        return out;
      };

      const parsed = parseCoverLetter(app.cover_letter || "");
      setFormData((p) => ({
        ...p,
        name: parsed.name || p.name,
        email: parsed.email || p.email,
        aboutMe: parsed.aboutMe || p.aboutMe,
        motivation: parsed.motivation || (app.cover_letter || p.motivation),
      }));

      // If we have custom questions, try to map answers by matching question text
      if (customQuestions.length > 0) {
        const parsedQ = parsed.qaByText || {};
        const mapped = {};
        customQuestions.forEach((q) => {
          if (parsedQ[q.question]) mapped[q.id] = parsedQ[q.question];
        });
        if (Object.keys(mapped).length) setCustomAnswers(mapped);
      }
    }
    if (job) {
      setOpportunity({
        id: job.id,
        title: job.title,
        company: job.company,
        location: job.location,
      });
    } else if (!job && opportunityId) {
      // Fetch opportunity from API
      opportunities.get(opportunityId)
        .then((data) => {
          setOpportunity({
            id: data.id,
            title: data.title,
            company: data.created_by_name || "Organization",
            location: "Remote",
          });
        })
        .catch(() => {
          setOpportunity({
            id: opportunityId,
            title: "Volunteer Opportunity",
            company: "Organization",
            location: "Remote",
          });
        });
    }
    
    // Get user profile from API
    apiClient.profile.pathfinderGet()
      .then(async (profile) => {
        if (profile) {
          const fullName = [profile.first_name, profile.last_name].filter(Boolean).join(" ");
          if (fullName) setFormData((p) => ({ ...p, name: fullName }));
          if (profile.base_details?.contact_email) setFormData((p) => ({ ...p, email: profile.base_details.contact_email }));
          else if (profile.email) setFormData((p) => ({ ...p, email: profile.email }));
        }
        // also read existing CV from credentials
        try {
          const credList = await apiClient.profile.credentialsList();
          const credsArray = Array.isArray(credList) ? credList : credList?.results || [];
          const cvCred = credsArray.find((c) =>
            (c.document_name || c.name || "").toLowerCase().includes("cv")
          );
          if (cvCred && cvCred.document) {
            setProfileCvUrl(cvCred.document);
            setProfileCvName(cvCred.document_name || cvCred.name || "CV");

            setProfileCvId(cvCred.id)
          }
        } catch (_) {
          // ignore
        }
      })
      .catch(() => {
        // Profile fetch failed, continue without pre-filling
      });
    
    setLoading(false);
  }, [opportunityId, location.state, customQuestions]);

  useEffect(() => {
    document.title = isEditMode ? "View Application - AfriVate" : "Apply - AfriVate";
  }, [isEditMode]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleCustomAnswer = (questionId, value) => {
    setCustomAnswers((prev) => ({ ...prev, [questionId]: value }));
  };

  const handleFileChange = (e) => {
    const file = e.target.files?.[0];
    setCvFile(file || null);
  };

  // upload a file to the profile credentials as the user's CV and update state
  const uploadProfileCv = async (file) => {
    if (!file) return null;
    setUploadingProfileCv(true);
    try {
      const credList = await apiClient.profile.credentialsList();
      const existing = Array.isArray(credList) ? credList : credList?.results || [];
      for (const cred of existing) {
        if ((cred.document_name || cred.name || "").toLowerCase().includes("cv")) {
          try { await apiClient.profile.credentialsDelete(cred.id); } catch (err) {}
        }
      }
      const fd = new FormData();
      fd.append("document_name", "CV");
      fd.append("document", file);
      await apiClient.profile.credentialsCreate(fd);
      
      const newList = await apiClient.profile.credentialsList();
      const arr = Array.isArray(newList) ? newList : newList?.results || [];
      const newCv = arr.find((c) => (c.document_name || c.name || "").toLowerCase().includes("cv"));
      
      if (newCv && newCv.document) {
        setProfileCvUrl(newCv.document);
        setProfileCvName(newCv.document_name || newCv.name || "CV");
        setProfileCvId(newCv.id); 
        setCvFile(null);
        return newCv.id; 
      }
      return null;
    } catch (err) {
      console.error("CV upload failed", err);
      return null;
    } finally {
      setUploadingProfileCv(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    let finalCvId = profileCvId;

    // If the user picked a new CV but didn't manually upload yet, upload it now
    if (cvFile) {
      try {
        const newId = await uploadProfileCv(cvFile);
        if (newId) finalCvId = newId; 
      } catch (err) {
        console.error("Error uploading CV before submission", err);
      }
    }

    if (!formData.name.trim() || !formData.email.trim()) {
      setToast({ isOpen: true, message: "Please enter your name and email.", type: "error" });
      return;
    }
    if (!formData.motivation.trim()) {
      setToast({ isOpen: true, message: "Please explain why you're applying.", type: "error" });
      return;
    }

    const lines = [];
    if (formData.name.trim() || formData.email.trim()) {
      lines.push("Contact details:");
      if (formData.name.trim()) lines.push(`Full name: ${formData.name.trim()}`);
      if (formData.email.trim()) lines.push(`Email: ${formData.email.trim()}`);
      lines.push("");
    }
    if (formData.aboutMe.trim()) {
      lines.push("About me:");
      lines.push(formData.aboutMe.trim());
      lines.push("");
    }
    if (formData.motivation.trim()) {
      lines.push("Why I am applying:");
      lines.push(formData.motivation.trim());
      lines.push("");
    }
    if (customQuestions.length > 0) {
      lines.push("Additional questions and answers:");
      customQuestions.forEach((q) => {
        const ans = (customAnswers[q.id] || "").trim();
        lines.push(`Q: ${q.question}`);
        lines.push(`A: ${ans || "(no answer provided)"}`);
        lines.push("");
      });
    }
    const coverLetter = lines.join("\n").trim() || formData.motivation || "";

    const applicationData = {
      opportunity: parseInt(opportunityId),
      cover_letter: coverLetter,
    };

    if (finalCvId) {
      applicationData.profile_resume = finalCvId;
    }

    try {
      if (existingApplication?.id) {
        await applications.patch(existingApplication.id, applicationData);
        setToast({ isOpen: true, message: "Application updated successfully!", type: "success" });
      } else {
        await applications.create(applicationData);
        setToast({ isOpen: true, message: "Application submitted successfully!", type: "success" });
      }
      setTimeout(() => navigate("/my-applications"), 1500);
    } catch (error) {
      console.error("Application submission error:", error);
      setToast({
        isOpen: true,
        message: getApiErrorMessage(error) || "Failed to submit application. Please try again.",
        type: "error",
      });
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-white font-sans">
        <NavBar />
        <div className="pt-20 px-4 py-12 text-center text-gray-500">Loading...</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white font-sans">
      <NavBar />
      <div className="pt-20 px-4 md:px-8 pb-8">
        <div className="max-w-2xl mx-auto">
          <button
            onClick={() => navigate(-1)}
            className="mb-4 text-[#6A00B1] hover:text-[#5A0091] transition-colors"
          >
            <i className="fa fa-arrow-left text-xl"></i>
          </button>
          <h1 className="text-2xl md:text-3xl font-bold text-black mb-2">
            {isEditMode ? "View & Edit Application" : "Apply for this Opportunity"}
          </h1>
          <p className="text-gray-600 mb-6">
            {opportunity?.title} at {opportunity?.company}
          </p>

          <form onSubmit={handleSubmit} className="space-y-6">
            <div>
              <label className="block text-sm font-bold text-black mb-2">Full Name *</label>
              <input
                type="text"
                name="name"
                value={formData.name}
                onChange={handleChange}
                required
                placeholder="Your full name"
                className="w-full border border-gray-300 rounded-lg px-4 py-2.5 focus:outline-none focus:ring-2 focus:ring-[#6A00B1]"
              />
            </div>
            <div>
              <label className="block text-sm font-bold text-black mb-2">Email *</label>
              <input
                type="email"
                name="email"
                value={formData.email}
                onChange={handleChange}
                required
                placeholder="your@email.com"
                className="w-full border border-gray-300 rounded-lg px-4 py-2.5 focus:outline-none focus:ring-2 focus:ring-[#6A00B1]"
              />
            </div>
            <div>
              <label className="block text-sm font-bold text-black mb-2">About yourself</label>
              <textarea
                name="aboutMe"
                value={formData.aboutMe}
                onChange={handleChange}
                placeholder="Brief introduction, skills, experience..."
                rows="4"
                className="w-full border border-gray-300 rounded-lg px-4 py-2.5 focus:outline-none focus:ring-2 focus:ring-[#6A00B1] resize-none"
              />
            </div>
            <div>
              <label className="block text-sm font-bold text-black mb-2">Why are you applying? *</label>
              <textarea
                name="motivation"
                value={formData.motivation}
                onChange={handleChange}
                required
                placeholder="Explain your interest and how you can contribute..."
                rows="4"
                className="w-full border border-gray-300 rounded-lg px-4 py-2.5 focus:outline-none focus:ring-2 focus:ring-[#6A00B1] resize-none"
              />
            </div>
            <div>
              <label className="block text-sm font-bold text-black mb-2">Upload CV / Resume</label>
              {profileCvUrl && !cvFile && (
                <div className="mb-2 p-3 bg-green-50 border border-green-200 rounded-lg flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <i className="fa fa-file-pdf-o text-green-600 text-xl"></i>
                    <div>
                      <p className="text-sm font-medium text-green-800">Using profile CV</p>
                      <a
                        href={profileCvUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-xs text-green-600 hover:underline"
                      >
                        {profileCvName || "View CV"}
                      </a>
                    </div>
                  </div>
                  <button
                    type="button"
                    className="text-purple-600 text-xs hover:underline"
                    onClick={() => setProfileCvUrl(null)}
                  >
                    Replace
                  </button>
                </div>
              )}
              <input
                type="file"
                accept=".pdf,.doc,.docx"
                onChange={handleFileChange}
                className="w-full text-sm text-gray-600 file:mr-4 file:py-2 file:px-4 file:rounded-lg file:border-0 file:bg-[#6A00B1] file:text-white file:font-semibold hover:file:bg-[#5A0091]"
              />
              {cvFile && <p className="mt-2 text-sm text-gray-500">{cvFile.name}</p>}
              {uploadingProfileCv && <p className="text-xs text-gray-500">Uploading to profile...</p>}
              {cvFile && (
                <button
                  type="button"
                  onClick={() => uploadProfileCv(cvFile)}
                  disabled={uploadingProfileCv}
                  className="mt-2 bg-[#6A00B1] text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-[#5A0091] disabled:opacity-50"
                >
                  {uploadingProfileCv ? "Uploading..." : "Upload to profile"}
                </button>
              )}
            </div>

            {customQuestions.length > 0 && (
              <div className="border-t border-gray-200 pt-6">
                <h3 className="text-lg font-bold text-black mb-4">Additional Questions</h3>
                {customQuestions.map((q) => (
                  <div key={q.id} className="mb-4">
                    <label className="block text-sm font-bold text-black mb-2">{q.question}</label>
                    <textarea
                      value={customAnswers[q.id] || ""}
                      onChange={(e) => handleCustomAnswer(q.id, e.target.value)}
                      placeholder="Your answer..."
                      rows="3"
                      className="w-full border border-gray-300 rounded-lg px-4 py-2.5 focus:outline-none focus:ring-2 focus:ring-[#6A00B1] resize-none"
                    />
                  </div>
                ))}
              </div>
            )}

            <div className="flex gap-3 pt-4">
              <button
                type="button"
                onClick={() => navigate(-1)}
                className="border-2 border-[#6A00B1] text-[#6A00B1] px-6 py-2.5 rounded-lg font-semibold hover:bg-purple-50 transition-colors"
              >
                Cancel
              </button>
              <button
                type="submit"
                className="bg-[#6A00B1] text-white px-6 py-2.5 rounded-lg font-semibold hover:bg-[#5A0091] transition-colors"
              >
                {existingApplication?.id ? "Re-submit Application" : "Submit Application"}
              </button>
            </div>
          </form>
        </div>
      </div>
      <Toast
        isOpen={toast.isOpen}
        message={toast.message}
        type={toast.type}
        onClose={() => setToast({ ...toast, isOpen: false })}
      />
    </div>
  );
};

export default ApplyApplication;
